### ISSUE TITLE
Include the botting rules

### ISSUE THREAD

**Issue by mybearworld** [meower-media/website#90]
It is generally considered bad practice to have implicit rules that accounts get banned for. This is because they may lead to perfectly preventable "rule" breaks that would have been removed, had the account owner known about them. Additionally, these "rules" might only be enforced in certain circumstances and ignored in others, as they are not rules stated in any official capacity.

**Comment by williamhorning** [comment]
legal matters don’t really belong in this repo imo, but regardless, the terms do state that anyone can be banned at any time for any reason:

> We reserve the right to suspend or terminate accounts for any reason, whether expressed or implied, with or without prior warning. Our commitment is to enforce these terms to maintain the integrity and safety of Meower.

so i don’t see this as an issue. if you have specific suggestions for stuff to be added/changed, feel free to open an issue
